package interfaz.gui;

/**
 * Created by German Jongewaard de Boer  
 */

import biblioteca.constantes.TipoDisco;
import biblioteca.listas.Categoria;
import biblioteca.objetos.Audio;
import biblioteca.objetos.Dato;
import biblioteca.objetos.DiscoCompacto;
import biblioteca.objetos.Pelicula;

import biblioteca.persistencia.Archivo;
import interfaz.modelos.ListaModeloCategorias;
import javax.swing.ListModel;

public class FormDiscoCompacto extends javax.swing.JFrame {

    private FrmPrincipal frmParent;
    private DiscoCompacto mCD;

    public FormDiscoCompacto() {
        initComponents();
        setLocationRelativeTo(null);
        rbMusica.setSelected(true);
        mCD = null;
        cargarCategorias();

    }

    public void setPadre(FrmPrincipal pPadre) {
        frmParent = pPadre;
    }

    public void setDiscoCompacto(DiscoCompacto cd) {
        mCD = cd;
        lblTitulo.setText("Editar CD");
        txtNombre.setText(mCD.getTitulo());
        txtGenero.setText(mCD.getGenero());
        txtAño.setText(mCD.getAno());
        txtEdicion.setText(mCD.getEdicion());
        
        if(cd instanceof Audio){
            rbMusica.setSelected(true);
        }else if(cd instanceof Dato){
            rbDatos.setSelected(true);
        }else if(cd instanceof Pelicula){
            rbPeliculas.setSelected(true);
        }
        
        int selected[] = new int[Archivo.getDatos().getCategorias().size()];
        int j = 0;
        for (Categoria c : mCD.getCategorias()) {
            selected[j++] = Archivo.getDatos().getCategorias().indexOf(c);
        }
        lstCategorias.setSelectedIndices(selected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        tabDatos = new javax.swing.JTabbedPane();
        pnlInfo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        lblEdicion = new javax.swing.JLabel();
        txtEdicion = new javax.swing.JTextField();
        rbMusica = new javax.swing.JRadioButton();
        rbDatos = new javax.swing.JRadioButton();
        rbPeliculas = new javax.swing.JRadioButton();
        pnlCategorias = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        lblCategorias = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario CD");

        lblTitulo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblTitulo.setText("Crear Disco Compacto");

        lblNombre.setText("Título");

        lblGenero.setText("Genero");

        lblAño.setText("Año");

        lblEdicion.setText("Edición");

        buttonGroup1.add(rbMusica);
        rbMusica.setText("Música");

        buttonGroup1.add(rbDatos);
        rbDatos.setText("Datos");

        buttonGroup1.add(rbPeliculas);
        rbPeliculas.setText("Películas");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(rbMusica)
                .addGap(18, 18, 18)
                .addComponent(rbPeliculas)
                .addGap(18, 18, 18)
                .addComponent(rbDatos)
                .addGap(181, 181, 181))
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEdicion)
                    .addComponent(txtAño)
                    .addComponent(txtGenero)
                    .addComponent(txtNombre)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblGenero)
                            .addComponent(lblAño)
                            .addComponent(lblEdicion))
                        .addContainerGap())))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPeliculas)
                    .addComponent(rbDatos)
                    .addComponent(rbMusica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabDatos.addTab("Información General", pnlInfo);

        lstCategorias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstCategorias);

        lblCategorias.setText("Seleccione las Categorias");

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategorias)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabDatos.addTab("Categorías", pnlCategorias);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(tabDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabDatos)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        //Validar datos
        DiscoCompacto cd = null;

        //MUSICA
        if (rbMusica.isSelected()) {

            if (mCD != null) {
                cd = mCD;
                cd.setTitulo(txtNombre.getText());
                cd.setGenero(txtGenero.getText());
                cd.setAno(txtAño.getText());
                cd.setEdicion(txtEdicion.getText());
            } else {
                cd = new Audio(TipoDisco.CD, txtGenero.getText(), txtAño.getText(), txtEdicion.getText(), txtNombre.getText());
                Archivo.getDatos().getItems().add(cd);
            }

            for (Object item : Archivo.getDatos().getCategorias()) {

                cd.borrarCategoria((Categoria) item);

            }

            for (Object item : lstCategorias.getSelectedValuesList()) {
                if (!cd.getCategorias().contains(item)) {
                    cd.agregarCategoria(((Categoria) item));
                }
            }

        } else if (rbDatos.isSelected()) {
            if (mCD != null) {
                cd = mCD;
                cd.setTitulo(txtNombre.getText());
                cd.setGenero(txtGenero.getText());
                cd.setAno(txtAño.getText());
                cd.setEdicion(txtEdicion.getText());
            } else {
                cd = new Dato(TipoDisco.DVD, txtGenero.getText(), txtAño.getText(), txtEdicion.getText(), txtNombre.getText());
                Archivo.getDatos().getItems().add(cd);
            }

            for (Object item : Archivo.getDatos().getCategorias()) {

                cd.borrarCategoria((Categoria) item);

            }

            for (Object item : lstCategorias.getSelectedValuesList()) {
                if (!cd.getCategorias().contains(item)) {
                    cd.agregarCategoria(((Categoria) item));
                }
            }
            //PELICULAS
        } else if (rbPeliculas.isSelected()) {
            if (mCD != null) {
                cd = mCD;
                cd.setTitulo(txtNombre.getText());
                cd.setGenero(txtGenero.getText());
                cd.setAno(txtAño.getText());
                cd.setEdicion(txtEdicion.getText());
            } else {
                cd = new Pelicula(TipoDisco.DVD, txtGenero.getText(), txtAño.getText(), txtEdicion.getText(), txtNombre.getText());
                Archivo.getDatos().getItems().add(cd);
            }

            for (Object item : Archivo.getDatos().getCategorias()) {

                cd.borrarCategoria((Categoria) item);

            }

            for (Object item : lstCategorias.getSelectedValuesList()) {
                if (!cd.getCategorias().contains(item)) {
                    cd.agregarCategoria(((Categoria) item));
                }
            }
        }

        frmParent.refrescar();
        frmParent.cargarCategorias();

        Archivo.guardar();
        this.dispose();

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FormDiscoCompacto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList lstCategorias;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JRadioButton rbDatos;
    private javax.swing.JRadioButton rbMusica;
    private javax.swing.JRadioButton rbPeliculas;
    private javax.swing.JTabbedPane tabDatos;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void cargarCategorias() {
        ListModel modelo = new ListaModeloCategorias();
        lstCategorias.setModel(modelo);
        lstCategorias.setSelectedIndex(0);
    }

    private boolean validar() {
        return true;
    }
    
}
